import "~/styles/globals.css";
import { Header } from "~/widgets/header"

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Header />
        <main className="
        flex min-h-screen flex-col items-center justify-center bg-gradient-to-b
        from-[#44ff44] to-[#f54444]
        dark:from-[#2e026d] dark:to-[#15162c]
        text-white
        ">
          {children}
        </main>
      </body>
    </html>
  );
}
